### ISSUE TITLE
TeX Live compatibility

### ISSUE THREAD

**Issue by ekce** [andrewrynhard/atom-latex-plus#13]
I normally only write LaTeX on Linux and decided to set it up on windows recently. I decided on using the TeX Live distribution instead of the MiKTex distribution (it seems that MiKTeX is what TeXlicious is configured to use by default on windows).

Unfortunately I've been having lots of trouble getting it to work. TeX Live comes with its own minimal perl and it's own latexmk. After setting the TeX Path to

```
  C:\texlive\2014\bin\win32\tex
```

and installing Strawberry Perl (TeXlicious was unable to find TeX Live's perl) I was still unable to work. From what I can deduce it seems that TeXlicious is using it's own latexmk and that one is unable to call pdflatex. Here are the errors from the developer console.

```
Compiling ...
C:\Users\ekce\.atom\packages\texlicious\lib\latexmk.coffee:21

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "perl "C:\Users\ekce\.atom\packages\texlicious\vendor\latexmk.pl" -interaction=nonstopmode -f -cd -pdf -file-line-error "C:\Data\latex\preamble\class\sample\preamble.tex""
Latexmk: This is Latexmk, John Collins, 10 January 2015, version: 4.42.
Latexmk: Changing directory to 'C:\Data\latex\preamble\class\sample\'
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
      'preamble.pdf'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -interaction=nonstopmode -file-line-error -recorder  "preamble.tex"'
------------
'pdflatex' is not recognized as an internal or external command,
operable program or batch file.
Failure to make 'preamble.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: (Pdf)LaTeX failed to generate the expected log file 'preamble.log'
Latexmk: Did not finish processing file 'preamble.tex':
   (Pdf)LaTeX failed to generate the expected log file 'preamble.log'
Latexmk: Undoing directory change
 {killed: false, code: 12, signal: null, cmd: "C:\Windows\system32\cmd.exe /s /c "perl "C:\Users\…:\Data\latex\preamble\class\sample\preamble.tex""", stack: (...)…}
C:\Users\ekce\.atom\packages\texlicious\lib\latexmk.coffee:21
(anonymous function)
child_process.js:736
exithandler
events.js:87 
emitTwo
events.js:169
emit
child_process.js:997
maybeClose
child_process.js:1070
ChildProcess._handle.onexit
C:\Users\ekce\.atom\packages\texlicious\lib\main.coffee:355
 ... error compiling.
C:\Users\ekce\.atom\packages\texlicious\lib\log-tool.coffee:45 Parsing log file ...
```

and here is the error that shows up in the popup window:

```
Error: ENOENT: no such file or directory, open 'C:\Data\latex\preamble\class\sample\preamble.log'
```

However, if I open a windows command prompt and call TeX Live's latexmk (with the same parameters on the same file) then the file compiles without errors. I believe that if I were to modify TeXlicious so that it called TeX Live's latexmk then it would work but this doesn't seem to be a very good solution. Is there some better way to fix this or is TeX Live just not supported with TeXlicious?

Atom Version: 0.206.0
System: Windows 7 X64 Ultimate
TeXlicious Version: v0.4.2
LaTeX implementation: Tex Live 2014

**Comment by andrewrynhard** [comment]
@ekce thank you for reporting this issue. Let me get texlive installed and try to recreate this. I believe it should be a quick fix.

**Comment by andrewrynhard** [comment]
@ekce are you certain that the correct path is `C:\texlive\2014\bin\win32\tex` installing TeXlive now and the path is `C:\texlive\2014\bin\win32`

**Comment by andrewrynhard** [comment]
@ekce I believe I have a fix. Please double check the path you used. In my installation it is `C:\texlive\2014\bin\win32`. There was also a problem with the code as well. I pushed the fix to the master branch. Are you comfortable with installing TeXlicious via `amp link`?

**Comment by andrewrynhard** [comment]
@ekce closing this issue. A fix has been published. Please update via Atom.

**Comment by ekce** [comment]
Wow, that was really fast. I'm sorry for taking so long to respond but I wasn't home.

I updated TeXlicious and updated the path and can confirm that it definitely works now!

I guess I was initially under the impression that I was supposed to link the TeX binary, not the folder of the TeX installation.

**Comment by andrewrynhard** [comment]
@ekce good to hear. By the way TeXlicious uses the same PATH as Atom so there is no need to add the path to the tex bin. The `Tex Path` option is useful when your installation is not in a standard location. I should probably make it more clear in the documentation.
