### ISSUE TITLE
Question: How to make Synctex work?

### ISSUE THREAD

**Issue by uliska** [andrewrynhard/atom-latex-plus#15]
I have checked the "Enable synctex" option and see that the corresponding `synctex.gz` file is updated upon running latex through TeXlicious.  But I have no idea how to make any use of that feature. (I know what this does in TeXStudio and would assume I need some viewer for the PDF that can then be synced with the source file.

Is there something or a package in Atom to view the compiled PDF and sync it? Or do I have options to configure an external PDF viewer to do so? I'm running Linux Mint.

**Comment by andrewrynhard** [comment]
@uliska: this feature is not fully implemented yet. The goal was a fully integrated solution using atom. Time hasn't permitted me to start work on this yet. See `pdf-viewer`. It is what I use to view the pdf within atom. The goal is to eventually use synctex with this but this will not happen any time soon.

**Comment by uliska** [comment]
OK, that makes sense. I suggest saying that in the readme, as in #16

**Comment by dpo** [comment]
There's an easy way to make this happen. [`pdf-view`](https://atom.io/packages/pdf-view) supports SyncTeX. It's enough to create a symbolic link (or copy) the `.synctex.gz` file to the folder where the source files reside. Clicking on the PDF takes you to the corresponding place in the source file.

**Comment by andrewrynhard** [comment]
@uliska @dpo there is also an open pull request that implements bi-directional synctex. The issues we are facing are mentioned. Feel free to check it out and work on it. Unfortunate I have been extremely busy for the last few months and have not had a chance to look at it.
