### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by auzias** [andrewrynhard/atom-latex-plus#18]
I just install the package, that seems awesome btw, and tried to compile. I then got this error.
Note that I'm not sure about the `texInputs` and I'm unsure on how to locate it.

**Atom Version**: 1.0.7
**System**: Debian GNU/Linux
**Thrown From**: [texlicious](https://github.com/andrewrynhard/atom-texlicious) package, v0.5.5
### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:449

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:449:13)
  at TeXlicious.loadProject (/home/auzias/.atom/packages/texlicious/lib/main.coffee:62:37)
  at TeXlicious.compile (/home/auzias/.atom/packages/texlicious/lib/main.coffee:132:6)
  at atom-text-editor.atom.commands.add.texlicious:compile (/home/auzias/.atom/packages/texlicious/lib/main.coffee:47:69)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -7:48.2.0 core:paste (atom-text-editor#texlicious.texInputs.editor.mini.is-focused)
     -7:25.7.0 texlicious:compile (atom-text-editor.editor.is-focused)
     -6:44.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
 11x -6:43.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:40.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -6:40.7.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -6:35.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -6:34.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:33.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 30x -6:28.6.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
  2x -5:17.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:17.3.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
 28x -5:16.4.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -4:57.9.0 core:delete (atom-text-editor.editor.is-focused)
     -4:54.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:25.2.0 texlicious:compile (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "texlicious": {
    "bibtexEnabled": true,
    "shellEscapeEnabled": true,
    "texPath": "/usr/bin/tex",
    "texInputs": "/usr/local/share/texmf/"
  }
}
```
### Installed Packages

``` coffee
# User
language-latex, v0.6.1
latexer, v0.2.4
texlicious, v0.5.5

# Dev
No dev packages
```

**Comment by auzias** [comment]
I got a better job that the package offer, and this could be turned into a feature.
I use `$inotifywait` to detect modifications on files (when you save it) to compile your .tex automatically. The compilation can obviously crash, though, if your changes are not finished/completed/correct.

Just an feature idea for the package:
if (.tex file saved ); then compile.

**Comment by andrewrynhard** [comment]
@auzias:  Hello and thank you for the reporting this issue! Please be aware that texInputs is not required. The way texInputs works is that if it exists as environment variable, `TEXINPUTS`, then latex looks for any custom `.sty`, `.cls`, etc. within that directory. As far as the bug you have come across could you please tell me more about your setup? Specifically what was your "project" structure like?

**Comment by andrewrynhard** [comment]
@auzias: In past versions of TeXlicious there was a `watch` feature that used Atom's api to handle a continuous compile. It worked but it would use too much cpu. This is a plan that has high priority and I am still trying to think of the best way to handle it. Pull requests are welcome and I am open to discussion on how to best handle the implementation of this idea!

**Comment by andrewrynhard** [comment]
@auzias: By the way a minimal working example included with a structure that simulates your project structure would be appreciated. If you could zip up the folder structure and post it, that would help.

**Comment by auzias** [comment]
@andrewrynhard: Specifically what was your "project" structure like?
I'm not sure to understand your question. Do you mean "atom" project or just "project". I put as many details as possible in the first post, so here is my just-project: https://github.com/auzias/network-courses (I was working on the slides). For the zip of the project, I suggest you check the github, tell me if I can give you any further help.

For the feature and its CPU usage, I'm sorry but I really don't know atom (nor electron, nor chromium) API. I wish you best luck, and I'll try to work on it if I have spare time between work and projects.

Thanks for your reply, and, again, thanks for your work !!

**Comment by andrewrynhard** [comment]
@auzias: Sorry, I meant the atom "project". Did you have slides or network-courses open in atom? I would like to try to reproduce your setup so I can debug it.

**Comment by auzias** [comment]
In a terminal:

``` bash
mkdir temp
cd temp
git clone https://github.com/auzias/network-courses.git
cd network-courses
atom $(pwd)
```

I just pushed the tex.json :+1:

**Comment by andrewrynhard** [comment]
@auzias: A new release should be available for download. This should fix this issue. Thanks again for the help.
