### ISSUE TITLE
Uncaught TypeError: Cannot read property  TOSTRING  of undefined

### ISSUE THREAD

**Issue by muhsayd** [andrewrynhard/atom-latex-plus#20]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 1.0.7 **System**: Mac OS X 10.10.5 **Thrown From**:  latex-plus  https://github.com/andrewrynhard/atom-latex-plus  package, v0.7.2 ### Stack Trace Uncaught TypeError: Cannot read property  TOSTRING  of undefined     At /Users/muhsayd/.atom/packages/latex-plus/lib/parser.js:38 TypeError: Cannot read property  TOSTRING  of undefined at /Users/muhsayd/.atom/packages/latex-plus/lib/parser.js:38:30 at FSReqWrap.readFileAfterOpen  as oncomplete   fs.js:302:5      ### Commands     -7:40.3.0 core:CONFIRM  atom-text-editor.editor.mini.is-focused  -4:42.7.0 core:paste  atom-text-editor#latex.customEngine.editor.mini.is-focused  -3:12.2.0 latex:build  ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel  -2:35.7.0 core:move-down  atom-text-editor.editor.is-focused  -2:34.7.0 core:move-up  atom-text-editor.editor.is-focused  -1:29.8.0 core:copy  atom-text-editor.editor.is-focused  -1:00.7.0 settings-view:OPEN  atom-text-editor.editor.is-focused  -0:47.6.0 core:paste  atom-text-editor#latex-plus.texInputs.editor.mini.is-focused  15x -0:44.7.0 core:backspace  atom-text-editor#latex-plus.texInputs.editor.mini.is-focused  2x -0:19.5.0 core:CONFIRM  atom-text-editor#latex-plus.texInputs.editor.mini.is-focused  -0:03.1.0 window:decrease-font-size  ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel  -0:02.7.0 latex-plus:compile  ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel      ### Config    json { core : {}, latex-plus : { bibtexEnabled : true, shellEscapeEnabled : true, texInputs : /usr/local/texlive/2014/texmf-dist } }     ### Installed Packages    coffee # User latex, v0.25.1 latex-plus, v0.7.2 linter, v1.4.3 linter-chktex, v1.0.0 # Dev No dev packages

**Comment by andrewrynhard** [comment]
@muhsayd: This release breaks the project configuration. Could you please ensure that the key `projectPath` exists within your project configuration? Invoking the `edit` command should open it for editing.

**Comment by andrewrynhard** [comment]
@muhsayd: There is a new release. Could you please close this if it fixes this issue? Thanks!

**Comment by andrewrynhard** [comment]
@muhsayd: I am assuming this was fixed. Please reopen if you have any more issues.
