### ISSUE TITLE
LaTeXmk Error: Output path is not matching due to relative paths

### ISSUE THREAD

**Issue by pleonex** [andrewrynhard/atom-latex-plus#22]
Hi, first thanks for this package, it's really good :+1: 

Trying to compile a tex file makes the following error. It is not exactly an error, since the PDF is generated correctly, but _pdflatex_ is returning error code `256` so a big red box is displayed. The problems is because of the expected output is _home/benito/Documentos/Trabajo/RTI/Internship/.latex/Memoria.pdf_ but the actual output is _.latex/Memoria.pdf_.

This is the full log:

```
Latexmk: This is Latexmk, John Collins, 10 January 2015, version: 4.42.
Latexmk: Changing directory to '/home/benito/Documentos/Trabajo/RTI/Internship/'
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'Bibliography.tex'
      'Company.tex'
      'Conclusion.tex'
      'Internship.tex'
      'PersonalValoration.tex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -interaction=nonstopmode -file-line-error -recorder -output-directory="/home/benito/Documentos/Trabajo/RTI/Internship/.latex"  "Memoria.tex"'
------------
Latexmk: References changed.
Latexmk: Log file says output to '.latex/Memoria.pdf'
Latexmk: ===For rule 'pdflatex', actual output '.latex/Memoria.pdf'
       ======appears not to match expected output '/home/benito/Documentos/Trabajo/RTI/Internship/.latex/Memoria.pdf'
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      '.latex/Memoria.aux'
      '.latex/Memoria.out'
      '.latex/Memoria.toc'
      '/home/benito/Documentos/Trabajo/RTI/Internship/.latex/Memoria.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -interaction=nonstopmode -file-line-error -recorder -output-directory="/home/benito/Documentos/Trabajo/RTI/Internship/.latex"  "Memoria.tex"'
------------
Latexmk: Log file says output to '.latex/Memoria.pdf'
Latexmk: ===For rule 'pdflatex', actual output '.latex/Memoria.pdf'
       ======appears not to match expected output '/home/benito/Documentos/Trabajo/RTI/Internship/.latex/Memoria.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Undoing directory change
```

**Comment by pleonex** [comment]
Ok, after checking again #21 I see it's a duplicate. Sorry I am closing this.

**Comment by pleonex** [comment]
BTW I think I have fixed it, I saw the actual error running _latexmk_ manually:

```
latexmk -outdir=.latex -pdf Memoria.tex
```

I was mistakenly using _latin1_ and _utf8_ as input encodings at the same time.

**Comment by andrewrynhard** [comment]
@pleonex: glad you managed to figure out the problem. I think I should really print these types of errors to the message panel just like syntax errors. Sorry for the confusion!

**Comment by DAbidou** [comment]
I am sorry, for both absolute and relative output directories, LaTeXmk generates the PDF file without problems.

However, for absolute output directory, I always get a warning of 

> appears not to match expected output

Is there any way to remove such an annoying warning despite the fact the generated PDF is working and in the right folder?

Additionally, is it possible to make the PDF be generated in one folder while the other auxiliary files be generated in another one?
