### ISSUE TITLE
configuration Error: Invalid parameter 

### ISSUE THREAD

**Issue by belggianny** [andrewrynhard/atom-latex-plus#26]
when trying to compile I get the following error:
configuration Error: Invalid parameter
Unexpected token U
I'm on windows, my tex bin path is set to C:\texlive\2014\bin\win32 as shown in issue #13

**Comment by andrewrynhard** [comment]
@belggianny: thank you for creating an issue. This sounds like an issue with the configuration file. Could you please post it here? The command to see it is: `cmd-'`

**Comment by elmewo** [comment]
I can reproduce this:
It occurs, when the project path in the project configuration file is set up with \ instead of / or \\ . Only affects windows.

**Comment by andrewrynhard** [comment]
@elmewo: Awesome, thank you! I can look into and push a fix soon.

**Comment by belggianny** [comment]
Thanks for responding, 
This is my config file:
{
  "projectPath": "C:\Users\Gianny\OneDrive\School\Polarimeter",
  "title": "LaTeX-Plus Project",
  "root": "main.tex",
  "program": "pdflatex",
  "output": ".latex"
}
I tried replacing the \ in the path by both / and //, both options resulted in the following error:
Configuration Error: Invalid parameter
Invalid root: C:\Users\Gianny\OneDrive\School\Polarimeter\main.tex

but I assume this error is caused by the same issue

**Comment by step21** [comment]
Just some additional information - it does not seem to matter how the path is specified. f.e. "/c/Program Files/MiKTeX 2.9/miktex/bin/x64/" which can be used in most cases and should work if this is the issue, but it results in the same error.

**Comment by fabiofdsantos** [comment]
@belggianny 

Try replacing `/` with `//`.

**Comment by ghost** [comment]
Similar issue happened to me after renaming a file. Obviously my own fault, but a look into the config file fixed it 👍
