### ISSUE TITLE
Config parameters

### ISSUE THREAD

**Issue by dpo** [andrewrynhard/atom-latex-plus#35]
This is related to the third point of #31. I just updated `latex-plus` and my settings look like this:

![screen shot 2016-02-17 at 18 47 38](https://cloud.githubusercontent.com/assets/38760/13128914/5bca5a48-d5a7-11e5-8f28-cfcb59609843.PNG)

As you can see, there's a mixture of old and new settings in there. I don't see anything causing this in `latex-plus`. The package lives in `~/.atom/packages`. I also have a dev version in `~/github` but Atom wasn't running in dev mode when I took the screenshot.

Any ideas?

**Comment by andrewrynhard** [comment]
@dpo that is strange. Perhaps it has something to do with Atom's storage. Can't remember for certain, I'm away from my computer, but I believe there is a ~/.atom/storage directory. I would have to say this is a bug with Atom itself.

**Comment by dpo** [comment]
I followed [this thread](https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/13) to vaporize Atom. Or at least, enough of it. I reinstalled a fresh `latex-plus` and the spurious options are gone. This was a last resort. Nothing else worked for me.
