### ISSUE TITLE
Feature request: set default root to be the current file

### ISSUE THREAD

**Issue by shouya** [andrewrynhard/atom-latex-plus#38]
In the default config, one might be good to set the project root file to be the current file. In many cases user would like to edit and compile a single latex file to produce the PDF. To have this option available will bring the users more convenience IMO.

Location in source: https://github.com/andrewrynhard/atom-latex-plus/blob/d4590bd61d13fb37de61408cbf135edb9a636177/lib/project.js#L104

**Comment by andrewrynhard** [comment]
Closing. See #39.
