### ISSUE TITLE
Broken Crossplatform Compatibility 

### ISSUE THREAD

**Issue by marconn** [andrewrynhard/atom-latex-plus#4]
Windows 8.1 x64
Atom 0.177.0 

Where can i change the compiler?

When I click the package settings, it only shows me the keyshorcuts.

![image](https://cloud.githubusercontent.com/assets/7016419/6207495/892768e2-b568-11e4-8436-47421881ab3c.png)

Any help would be appreciated

Thanks

**Comment by andrewrynhard** [comment]
@arkandoscr: I suspect this is actually a problem with atom core. Can you try compiling an arbitrary file to activate the package? There is an issue with atom that the settings only get displayed properly when the package is 'active'. To activate it `compile` or `watch` must be invoked.

**Comment by marconn** [comment]
It didn't work :(. 
When I clicked `compile` or `watch`, nothing happened.
I already updated the package but the problem persists.

**Comment by andrewrynhard** [comment]
@arkandoscr: I just spun up a VM of Windows and found bug. Thanks for creating the issue. I will be pushing a fix soon. Atom should notify you of available updates. Please let me know if/when you update and if the update solves this issue.

**Comment by andrewrynhard** [comment]
@arkandoscr: The new patch should fix the problems you were having. Enjoy.

**Comment by andrewrynhard** [comment]
@arkandoscr: By the way please ensure you have perl installed. This package currently relies on latexmk which requires perl. It is in the plans to remove this depency on latexmk and perl in the future.

**Comment by marconn** [comment]
@arynhard The update is working, Now, I can choose the compiler and set the other settings (paths) :D 

However, when i click compile, an error occurs. I'll paste the info here, but i'm sure that it is related to another bug.

```
Uncaught Error: ENOENT, no such file or directory 'C:\Users\Marco\Desktop\Leeuwenhoek\Reportes\Reporte Training y Gmail\main.log'
fs.js:574
Hide Stack TraceShow Stack Trace
Error: ENOENT, no such file or directory 'C:\Users\Marco\Desktop\Leeuwenhoek\Reportes\Reporte Training y Gmail\main.log'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (C:\Users\Marco\AppData\Local\atom\app-0.179.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (C:\Users\Marco\AppData\Local\atom\app-0.179.0\resources\atom\common\lib\asar.js:329:27)
  at LogTool.module.exports.LogTool.getErrors (C:\Users\Marco\.atom\packages\texlicious\lib\log-tool.coffee:36:8)
  at C:\Users\Marco\.atom\packages\texlicious\lib\main.coffee:228:30
  at C:\Users\Marco\.atom\packages\texlicious\lib\latexmk.coffee:14:9
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1085:5)
```

**Comment by andrewrynhard** [comment]
@arkandoscr: Would you mind sending me what settings you have in place? I can probably fix this quickly. By the way have you install perl?

**Comment by marconn** [comment]
Config.cson

```
"*":
  "*":
    "exception-reporting":
      userId: "d94590e1-88d5-141a-fa01-06fb87d027c2"
    welcome:
      showOnStartup: false
    core:
      themes: [
        "atom-light-ui"
        "visual-studio-dark-syntax"
      ]
      disabledPackages: [
        "wrap-guide"
      ]
    editor:
      fontSize: 12
      showIndentGuide: true
    "save-session":
      dataSaveFolder: "c:\\Users\\Marco\\.atom\\packages\\save-session\\projects"
      project: "c:\\Users\\Marco\\Desktop"
      windowX: -8
      windowY: -8
      windowWidth: 867
      windowHeight: 886
      treeSize: 182
    "atom-beautify":
      _analyticsUserId: "5234db3f-df96-428a-ba2a-d11c594f9fa9"
  "autoclose-html": {}
  "save-session":
    dataSaveFolder: "c:\\Users\\Marco\\.atom\\packages\\save-session\\projects"
    windowX: -8
    windowY: -8
    windowWidth: 1616
    windowHeight: 886
    project: "C:\\Users\\Marco\\Desktop\\Leeuwenhoek\\Reportes\\Reporte Training y Gmail"
  "exception-reporting":
    userId: "e4cb2f73-1f5e-01d9-eaf8-d07b5d1ed47f"
  welcome:
    showOnStartup: false
  core:
    themes: [
      "seti-ui"
      "elly-syntax"
    ]
    disabledPackages: [
      "wrap-guide"
    ]
  editor:
    invisibles: {}
    fontSize: 14
  latex: {}
  texlicious:
    texPath: "C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64"
    texInputs: "C:\\Program Files\\MiKTeX 2.9\\tpm\\packages"
    shellEscapeEnabled: true
```

**Comment by andrewrynhard** [comment]
@arkandoscr: Thank you. Another question. Do you have perl installed?

**Comment by marconn** [comment]
Yes, I have active perl for windows.

**Comment by marconn** [comment]
@arynhard I unchecked the `Shell Escape` option, then restarted and now it works!!! :D 
Thanks for your help.

**Comment by andrewrynhard** [comment]
@arkandoscr: Good to hear. I tried running the compile with shell escape enabled but I cannot seem to reproduce the error. I am going to close this issue and if that occurs again feel free to open another issue.
