### ISSUE TITLE
Sync after compiling

### ISSUE THREAD

**Issue by svkurowski** [andrewrynhard/atom-latex-plus#42]
It would be nice to have the PDF view synced after compiling. The following steps would have to be performed:
- Before compiling, store current file path and cursor position
- Compile (as is done currently)
- Upon successful completion of the compilation, sync the PDF viewer to the stored file path / cursor position

Maybe we should also have a (boolean) setting for this s.t. users can decide whether they want to have this behavior or not.

**Comment by andrewrynhard** [comment]
@svkurowski This sounds like a good idea. I will put an `enhancement` label on this.
