### ISSUE TITLE
Invalid parameter Unexpected token E - TexLive isn't working

### ISSUE THREAD

**Issue by eddorneles** [andrewrynhard/atom-latex-plus#46]
I've already installed and used tex live with atom-latex-plus in my Linux.
But now I'm trying to start write LaTeX docs in Windows also. 
I've installed Tex Live in the default directory: C:\texlive\
I've already seen in my environment variable PATH, it has C:\texlive\2015\bin\win32 there.
I have also set inside the Package View of Latex-Plus
![2016-03-25](https://cloud.githubusercontent.com/assets/5637710/14034674/ab4b5500-f225-11e5-84de-b13ad75aab2d.png)

Every time when I try compiling I receive one message from Atom:
"Configuration Error: Invalid parameter
Unexpected token E"

When I drag and drop my .tex file over the pdflatex.exe it creates the pdf corectly.

I'm not sure, but maybe is the problem whiel latex-plus tries to link with latexmk.exe

Thanks, I'm waiting for instructions!

**Comment by andrewrynhard** [comment]
This seems related to #26. Would you mind posting your project config json? Use the `edit` command in the `latex-plus` package to pull it up. Thanks.

**Comment by eddorneles** [comment]
There it is:

```
{
  "projectPath": "E:\Estudo\LaTeX Docs\sample",
  "title": "LaTeX-Plus Project",
  "root": "sample.tex",
  "program": "pdflatex",
  "latexmkOptions": "-bibtex -pdf -shell-escape",
  "output": "latex"
}

```

Thanks for the answer

**Comment by eddorneles** [comment]
Oh! Was exactly the same issue, even if we're working in Windows we have to change those backslash for slashs, thank you very much I got it!

**Comment by andrewrynhard** [comment]
@eddorneles changing to backlashes works?

**Comment by eddorneles** [comment]
Yes! Has worked very fine!
Thank you very much!

**Comment by andrewrynhard** [comment]
@eddorneles: great thank you.
