### ISSUE TITLE
TeXlicious not doing anything?

### ISSUE THREAD

**Issue by TheChymera** [andrewrynhard/atom-latex-plus#5]
running compile (`ctrl`+`shift`+`p`, then typing in `compile`) I get no rebuild of my pdf file. I also get no error, but I _do_ get a gray bar in the bottom of my editor window. Sadly I cannot really interact with it or make it go away until I close the window.

Any Ideas what's going on and how I can debug this? If I run `pdflatex myfile.tex` from the command line everything works dandy.

**Comment by andrewrynhard** [comment]
@TheChymera  are you running OS X or Windows? Also If you could please open the developer tools (View -> Developer -> Toggle Developer Tools) and select the console tab, then try running a compile again. There should be some output. Can you post that here?

**Comment by andrewrynhard** [comment]
@TheChymera : By the way if you are running Atom on windows then please ensure you have perl installed. Currently TeXlicious depends on latexmk which depends on perl. It is planned to remove the dependency on  latexmk, but that is not in the near future.

**Comment by TheChymera** [comment]
I am running linux, and i have perl as well as latexmk installed. I am running on a machine with a hidpi display, and my drop-down menus are all wrong. I can't do View -> Developer -> Toggle Developer Tools via point and click. Is there a shortcut for it?

**Comment by andrewrynhard** [comment]
@TheChymera : Shfit-Ctl-I

**Comment by andrewrynhard** [comment]
@TheChymera : I found what the problem was. Forgot the inherit the parent process' environment for linux. I will push a fix in about 10 minutes.

**Comment by andrewrynhard** [comment]
@TheChymera: I also added keymaps to invoke the `compile`, `watch`, and `stop` commands. They are   `ctrl-shift-C`, `ctrl-shift-W`, and `ctrl-shift-S` respectively. Please let me know if the update fixes this issue.

**Comment by TheChymera** [comment]
Ok, it works now! (thanks!) But I till get that annoying gray bottom bar which gives me no info and which I cannot remove after I run the texlicious compile command, unless I close my window. See this screenshot:

![screenshot from 2015-02-20 22 45 52](https://cloud.githubusercontent.com/assets/950524/6309967/8b2874ae-b952-11e4-9efc-df90fc326181.png)

**Comment by andrewrynhard** [comment]
@TheChymera : The gray bar will be removed in a future release. This project is in its infancy so a lot of things will be break and might not be perfect. The gray bar is one of them I'm afraid. The next release will use the standard status bar at the bottom. For now you are right that it displays no information, but that is true only when your are not 'watching' a file. As of now it is used to indicate a compile is in process and/or the current file you are watching. I will close this issue. Look for the next release, it will remove the gray bar.
