### ISSUE TITLE
How to enable message panel instead of notifications?

### ISSUE THREAD

**Issue by armin-pfaeffle** [andrewrynhard/atom-latex-plus#50]
Hey!

First of all, thanks for your package!

In your README you demonstrate how to use the message panel including error messages. I'm using Windows 10 with MikTex and the only thing I can see are notifications and no real error messages, as you can see in the screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/531182/15176366/05e5a82a-176b-11e6-8b4f-b022d7e4950f.png)

How can I enable the message panel? Do I have to use a Text distribution?

**Comment by DeusProx** [comment]
I had a similiar problem too. The error was in my imports as I used `\usepackage{english}` instead of `\usepackage[english]{babel}`. Found this error by using pdflatex inside my terminal. Probably those kind of error messages can't be shown somehow at this state of the package.

**Comment by andrewrynhard** [comment]
This type of error is purposely made from `latex-plus`. The error message could be better, but the title states: `LaTeXmk Error`. These errors are not discoverable in the log file as they are non zero exit code values from latexmk. The errors in the message panel are errors in your latex code that latexmk discovers. These errors are no related to the exit code of latexmk. Does that clear this up?

**Comment by mdavis-xyz** [comment]
I'm having a similar issue.

I'm confused by the readme. The last gif has a printscreen showing a list of errors appearing, presumably after some keyboard shortcut.

What shortcut is used in that gif?

When I try to compile a valid file I get an error, but there's no obvious way to see what that error is. I don't get a pop-up notification (as above), or an error log (as in the readme).

How can I find out what's going on?

![printscreen with error message](https://cloud.githubusercontent.com/assets/7035647/15384935/703dad7c-1de1-11e6-81c7-d9ad9318e6b3.png)

**Comment by armin-pfaeffle** [comment]
@DeusProx , @andrewrynhard : Thanks! I will have a look at it!
