### ISSUE TITLE
pdf doesn't open on compile

### ISSUE THREAD

**Issue by DeusProx** [andrewrynhard/atom-latex-plus#51]
I'm using 16.04 Mate inside an VM with atom, language-latex, latex-plus and pdf-viewer but when running compile or compile-and-sync the pdf-view gets opened on the right side of the window but is completely blank! When directly clicking on the pdf everything works correctly. Still it would be really convenient if it would work like you designed it! See the picture:
![screenshot at 2016-05-12 03 00 02](https://cloud.githubusercontent.com/assets/6798066/15201222/d844deca-17ee-11e6-8cc5-2a955e636fec.png)

**Comment by andrewrynhard** [comment]
Closed by #54
