### ISSUE TITLE
Keybindings on linux aren't working

### ISSUE THREAD

**Issue by DeusProx** [andrewrynhard/atom-latex-plus#55]
I can't use any of the defined keybindings defined for the ubuntu mate 16.04 linux environment. Several similiar problems exist for other atom packages.
Using the keybinding-resolver ( ctrl-. ) I found out that pushing ctrl and alt will always end as the keybind ctrl-alt no matter in which order they are pushed.
For the next thing. I'm using a german keyboard and my whole system is configured for german since installation(few days ago). Trying to push [ctrl, alt, shift and ";"] together will end in the keybind "strg-alt-<". So it seems that somehow atom is using the american keylayout for the just for the ";". the same goes for [ctrl, alt, shift and ":"] which will end in the keybind "strg-alt->" and [ctrl, " ' "] which will end in "ctrl-/".

So none of the keybinds can work at the moment.

Looking into other related problem the reasons seems to lie in a use of non-standard key mappings in the code base of chromium. [Source](https://github.com/atom/atom/issues/2068)

**Comment by maaaaadn** [comment]
same here, german keyboard layout -> no keybindings... have you found any solution?

**Comment by DeusProx** [comment]
Closing since it's stale

**Comment by DeusProx** [comment]
Stale issue
