### ISSUE TITLE
Proposal to solve different current issues

### ISSUE THREAD

**Issue by DeusProx** [andrewrynhard/atom-latex-plus#57]
Currently there are a few issues which (in my opinion) makes it very hard to work with latex-plus despite that it is nonetheless a very stable package.
I would like to introduce the following changes:
1. General things
   - a) There should be global and per project settings on how to compile packages.
   - b) Per project settings should be placed inside each project folder with the name ".latex.plus.json".
     
     (The reason of not putting them "~/.atom/packages/latex-plus/projects/<x.json>" is a possible name clash. I for example create named directories for my family/friends where each one has it's own subdirectory "curriculum". All those subdirectories would want to create a curriculum.json in the projects directory of our package.)
   - c) Per project settings can be created/accessed with it's own keyboard shortcut(Refactor "Edit").
   - d) On creation of a per project setting the current open tex file should be root tex file of the project. Called "root".
2. Per Project & Global settings which should be added:
   - a) Optional build path which defaults to subdirectory "./latex.build" called "output" setting.
     
     Reason why I don't want to hide the directory is #56 
   - b) A field where we can decide if the pdf should be symlinked, copied or nothing should happen to the pdf. Named "postCompileAction" with possible options "copy", "link" and "none".
   - c) If copying or symlinking is activated we have the permission to delete anything which is in the way.
   - d) Default case is to do nothing with the pdf
   - e) A path where the pdf is symlinked/copied to. Default Path is "./" called "postCompileActionPath"
3. Behaviour on different settings cases:
   - a) Any Per Project settings overwrites global settings.
   - b) Any Per Project settings needs to define the "root" setting
   - d) If Per Project settings define a "postCompileAction" it needs also to define a "postCompileActionPath" or it uses the default behaviour "./".
   - e) Otherwise if per project settings doesn't define a certain setting global settings are applied. If there are no global settings default settings will be applied.
   - f) If there is no per project setting the global/default settings should be applied at the current open tex-file.

This Proposol plans to resolve:
#48 #49 #56 #58

Please share your thoughts if anything is unclear and say if it would fit your needs. The faster we agree on this the faster we can proceed and progress with our own latex-projects! :)

**Comment by andrewrynhard** [comment]
I agree with all of this. And I think it works with most of the concerns expressed in the other issues.

**Comment by andrewrynhard** [comment]
Closed by #71
