### ISSUE TITLE
Strange error?

### ISSUE THREAD

**Issue by TheChymera** [andrewrynhard/atom-latex-plus#6]
Hi, I keep getting this error if I try to build a file `ctrl-shift-C`:

```
Error: Command failed: /bin/sh -c perl "/home/chymera/.atom/packages/texlicious/vendor/latexmk.pl" -interaction=nonstopmode -f -cd -pdf -file-line-error "/home/chymera/docsrc/PhD-roadmap/roadmap.tex" Latexmk: This is Latexmk, John Collins, 10 January 2015, version: 4.42. Latexmk: Changing directory to '/home/chymera/docsrc/PhD-roadmap/' Rule 'pdflatex': File changes, etc: Changed files, or newly in use since previous run(s):

  'roadmap.tex'
Run number 1 of rule 'pdflatex'

Running 'pdflatex -interaction=nonstopmode -file-line-error -recorder "roadmap.tex"'

Latexmk: Found input bbl file 'roadmap.bbl' Latexmk: Log file says output to 'roadmap.pdf' Latexmk: Found bibliography file(s) [./bib.bib roadmap-blx.bib] Collected error summary (may duplicate other messages): pdflatex: Command for 'pdflatex' gave return code 256 Latexmk: Undoing directory change
```

What's up with that?

Also, it would be cool if texlicious could also integrate bibtex and pythontex support. At least the former is used by  many LaTeX users routinely.

**Comment by andrewrynhard** [comment]
@TheChymera: That is strange. The output is not very helpful either. What steps can be taken to reproduce this? Does it work if you compile it manually from the terminal?

**Comment by andrewrynhard** [comment]
@TheChymera: Just added `BibTeX` support as well. If you want it now you will have to install the repo version of the package and link the `develop` branch. It is not stable officially but I use it on a daily basis so it is stable enough. You might have a problem here or there but nothing that breaks so far.

**Comment by TheChymera** [comment]
@arynhard  so the standrd atom packge manager won't be able to update to the newest version just yet?

**Comment by andrewrynhard** [comment]
@TheChymera: Not yet, expect an update in about two weeks. For now if you would like BibTeX support you will have to clone the repo, checkout the develop branch, and then use `apm install` and `apm link` to install TeXlicious. I apologize for the inconvenience, however, there is a strange bug in the develop branch that causes minor issues when using multiple project roots. If you have open only the latex project you are working on then it works just fine.

**Comment by andrewrynhard** [comment]
@TheChymera : Did you ever manage to reproduce this error?

**Comment by TheChymera** [comment]
You mean my original error? yes. This ("there is a strange bug in the develop branch that causes minor issues when using multiple project roots."), however, no.

**Comment by andrewrynhard** [comment]
@TheChymera : BibTeX is now supported in the latest version. I will be closing this issue out. If you have problems, let me know and I will reopen this issue.
