### ISSUE TITLE
Package not working on ubuntu

### ISSUE THREAD

**Issue by pendar747** [andrewrynhard/atom-latex-plus#61]
I have tried both installing the package through atom or by first cloning and then running `apm install`, `apm link` as mentioned in the readme. However none of the package commands are available!

**Comment by andrewrynhard** [comment]
Is the package present in `~/.atom/packages`?

**Comment by pendar747** [comment]
Yes it is  

![](https://link.nylas.com/open/c0olxcq1gqfyt9ma2ddx10e7o/local-1f889acd-
637a?r=cmVwbHkrMDAxZThiMDRjNzE4ZmUzMDg3MjZiZDJjZGI5ODZiN2MyM2U3ZTU1NGRjNjNiZmVmOTJjZjAwMDAwMDAxMTM3YTk5NGM5MmExNjljZTA5N2ExNmIxQHJlcGx5LmdpdGh1Yi5jb20=)

**Comment by andrewrynhard** [comment]
Thanks. What do you mean by "available"? Are the commands missing in the menu or when you invoke them it does not work as expected?

**Comment by pendar747** [comment]
They neither appear in the menu or work when I use keyboard shortcuts.  

Pendar  

![](https://link.nylas.com/open/c0olxcq1gqfyt9ma2ddx10e7o/local-9a8ab54a-
a89e?r=cmVwbHkrMDAxZThiMDQzNjBjZTU5NTdlOWI2NmMxYTg1Njk2NWQ5ODU2NGNlMzNlNTVjOGQ1OTJjZjAwMDAwMDAxMTM3ZDI4MDk5MmExNjljZTA5N2ExNmIxQHJlcGx5LmdpdGh1Yi5jb20=)

**Comment by andrewrynhard** [comment]
That is strange. I will see info can reproduce this. Which version of Ubuntu? Which version of Atom?

**Comment by pendar747** [comment]
Atom    : 1.7.3  
Electron: 0.36.8  
Chrome  : 47.0.2526.110  
Node    : 5.1.1

and Ubuntu 16

Pendar  

![](https://link.nylas.com/open/c0olxcq1gqfyt9ma2ddx10e7o/local-
c46f5db6-81a6?r=cmVwbHkrMDAxZThiMDQ3OTUxZDE0NGQ0NjYzNjAwMGRiMTU3Y2VkNzJhYWVlNGI0NTA0ZTQ3OTJjZjAwMDAwMDAxMTM3ZDdjMjI5MmExNjljZTA5N2ExNmIxQHJlcGx5LmdpdGh1Yi5jb20=)

**Comment by andrewrynhard** [comment]
@pendar747 please ensure that the `language-latex` package is installed and you have a `. tex`file open.
