### ISSUE TITLE
The package can not work on MacOS.

### ISSUE THREAD

**Issue by roselifeye** [andrewrynhard/atom-latex-plus#65]
Hi,

I installed the package on two version of the MacOS. One is El captain on iMac. Another one is macOS Sierra. However, both of them don't work. After installation, there are no changes or even the keymap of commands. I already set the Tex bin. Still didn't work.

**Comment by andrewrynhard** [comment]
Have you tried opening a .tex file and compiling?

**Comment by andrewrynhard** [comment]
This was reported when MacOS was still beta. The package works fine now. Thank you.
