### ISSUE TITLE
Symlinking Error when compiling

### ISSUE THREAD

**Issue by syed-islam** [andrewrynhard/atom-latex-plus#66]
Error while symlinking /Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/it.synctex.gz to /Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/.latex/it.synctex.gz
Error: EINVAL: invalid argument, readlink '/Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/it.synctex.gz'
Error while symlinking /Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/it.pdf to /Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/.latex/it.pdf
Error: EINVAL: invalid argument, readlink '/Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/it.pdf'

**Comment by dpo** [comment]
Duplicate of #58?

**Comment by andrewrynhard** [comment]
Closed by #71
