### ISSUE TITLE
Error with Open Output on MacOS

### ISSUE THREAD

**Issue by marioyc** [andrewrynhard/atom-latex-plus#67]
Hi, I'm having error after building, for a short while I can see the pdf updates and is ok, but then it just goes black, so I need to click on it at each time.

![screen shot 2016-07-25 at 4 49 30 pm](https://cloud.githubusercontent.com/assets/382898/17105548/078c84d4-5288-11e6-9b99-a6f4efec088e.png)

**Comment by andrewrynhard** [comment]
@marioyc is this still an issue? I have updated my OS to Sierra and everything is fine.

**Comment by andrewrynhard** [comment]
This was reported when MacOS was still beta. The package works fine now. Thank you.
